services:

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    healthcheck:
      test: ["CMD-SHELL","sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}'"]
      timeout: 5s
      interval: 5s
      retries: 5
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
        volume: {}
      - type: bind
        source: ./be/db/objects/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
    # To test in localhost
    ports:
    - mode: host
      target: 5432 # Container port
      published: ${DB_PORT} # Host port
    profiles:
      - gha

  api:
    restart: always
    build:
      context: .
      dockerfile: ./be/Dockerfile
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      # To test in localhost
      # DB_PORT: ${DB_PORT}
    ports:
      - mode: host
        target: 8000 # Container port
        published: ${UVICORN_PORT} # Host port
    profiles:
      - gha

  fe:
      restart: always
      build:
        context: ./
        dockerfile: ./fe/Dockerfile
        args:
          - VITE_API_URL=${VITE_API_URL}
      ports:
      - mode: host
        target: 80 # Container port
        published: 8005 # Host port
      profiles:
        - gha


volumes:
  db_data:
    driver: local