name: Continuous Integration - Build and Publish Docker Images
run-name: CI - Build and Publish Docker Images

on:
  push:
    branches:
      - main
    paths:
      - "docker**"
      - "Dockerfile"
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Images
        run: |
          docker compose -f docker-compose.yml --env-file base.env --profile gha build
          docker compose -f docker-compose.yml --env-file base.env --profile gha push
