name: CI - Frontend
run-name: CI - FRONTEND - Lint, Build and Test
on:
  push:
    branches:
      - main
    paths:
      - "fe/**"
  pull_request:
    branches:
      - main
    paths:
      - "fe/**"
  workflow_dispatch:
jobs:
  lint-frontend:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Lint
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Install Node.js
        uses: actions/setup-node@main
        with:
          node-version: lts/*
      - name: Install dependencies
        run: |
          cd fe
          npm ci
      - name: Lint with ESLint
        run: |
          cd fe
          npx eslint .

  playwright-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build and Run Playwright tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: lts/*

      - name: Install Playwright Browsers and dependencies
        run: |
          cd fe
          npm ci
          npx playwright install --with-deps

      - name: Build the app
        run: |
          cd fe
          vite preview --port 5173
        # npm run build

      - name: Run Playwright tests
        run: |
          cd fe
          npx playwright test
          env:
            CI: true
  #     - uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: playwright-report ${{ github.run_number }}-${{ github.run_attempt }}
  #         path: fe/playwright-report/
  #         retention-days: 30
  #         overwrite: true
