name: "Flujo CI-Test"
run-name: "Flujo CI - Test"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  PYTHON_VERSION: "3.9"
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@main
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with Ruff
        run: |
          ruff

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@main
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest
