name: Print Envs
run-name: Print Envs

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  print-envs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify environment
        run: |
          echo "Environment variable DB_USERNAME: ${{ vars.DB_USERNAME }}"
